services:
  postgres:
    image: postgres
    container_name: postgresdb_app
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgresdb_app:5432/postgres
    container_name: app_backend
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgresdb_app:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres